services:

  postgres:
    image: postgres:17
    container_name: foms_ai_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: foms_ai
      POSTGRES_PASSWORD: foms_ai_password
      POSTGRES_DB: foms_ai_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8
    container_name: foms_ai_mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: foms_ai
      MONGO_INITDB_ROOT_PASSWORD: foms_ai_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  pgadmin:
    image: dpage/pgadmin4
    container_name: foms_ai_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@foms.local
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data:
  mongodb_data: