services:
  foms.api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: foms_api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=host.docker.internal\\SQLEXPRESS;Database=FOMSDB;Trusted_Connection=True;TrustServerCertificate=True;
      - JwtSettings__Secret=${JWT_SECRET:-FOMS_Capstone_JWT_SecureKey_2026!!}
      - JwtSettings__Issuer=FOMS.Api
      - JwtSettings__Audience=FOMS.Api
      - PayMongo__SecretKey=${PAYMONGO_SECRET_KEY:-sk_test_fyNzfY2nbwdhfgUcoMmWoZJq}
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
